services:
  carbontrackr_backend:
    build: .
    ports:
      - "4500:4500"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/carbontrackr

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
