services:
  carbontrackr_backend:
    build: .
    ports:
      - "4500:4500"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/carbontrackr
    networks:
      - app
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - carbontrackr_backend
    networks:
      - app

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app
    driver: bridge
    volumes:
      - mongo-data:/data/db/carbontrackr
volumes:
  mongo-data:
